import { Box } from '@mui/material';
import axios from 'axios';
import Footer from 'components/common/footer';
import Header from 'components/common/header';
import Head from 'next/head';
import React from 'react';
import { useQuery } from 'react-query';
import { Category } from 'types/categoryType';
import { Project } from 'types/projectType';
import ProjectsList from '../../components/allProject/allProject';

interface Props {
  projects: Project;
}

export default function Projects() {
  const { data: categories } = useQuery('categories', async () => {
    const { data } = await axios.get('/categories');
    return data as Category[];
  });
 
  return (
    <>
      <Head>
        <title>All Projects - Arcon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="header">
        <Header pageTitle="Our Projects" breadcrumbTitle="Our Projects" />
      </Box>
      <Box component="main">{categories && <ProjectsList categories={categories} />}</Box>
      <Box component="footer">
        <Footer />
      </Box>
    </>
  );
}
