import { Box } from '@mui/system';
import AboutUs from 'components/about/aboutUs';
import Info from 'components/about/info';
import Team from 'components/about/team';
import WorkStage from 'components/about/workStages';
import Footer from 'components/common/footer';
import Header from 'components/common/header';
import Services from 'components/home/services';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="header">
        <Header pageTitle="About Us" breadcrumbTitle="About Us" />
      </Box>
      <Box component="main">
        <AboutUs />
        <Services />
        <WorkStage />
        <Info />
        <Team />
      </Box>
      <Box component="footer">
        <Footer />
      </Box>
    </>
  );
};

export default About;
