import { Box } from '@mui/material';
import { getProjects } from 'backend/projects';
import Navbar from 'components/common/navbar';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { Project } from 'types/projectType';
import Footer from '../components/common/footer';
import AboutArcon from '../components/home/aboutArcon';
import Contact from '../components/home/contact';
import Header from '../components/home/header';
import Projects from '../components/home/projects';
import ServiceLogo from '../components/home/serviceLogo';
import Services from '../components/home/services';
import Testimonials from '../components/home/testimonials';
import WhyArcon from '../components/home/whyArcon';
import WorkingStyle from '../components/home/workingStyle';

interface Props {
  projects: Project[];
}

const Home: NextPage<Props> = ({ projects }) => {
  return (
    <Box>
      <Head>
        <title>Arcon Interior</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <main>
        <AboutArcon />
        <Services />
        <Projects projects={projects} />
        <WorkingStyle />
        <Testimonials />
        <WhyArcon />
        <ServiceLogo />
        <Contact />
      </main>
      <Footer />
    </Box>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const projects = await getProjects();
  return {
    props: {
      projects,
    },
  };
};

export default Home;
