const teamData = [
  {
    name: 'Dr.Delowar',
    position: 'Senior Engineer',
    img: '/images/delowar.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Brandi Boyd',
    position: 'Designer',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Alenalia Jhon',
    position: 'Manager',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Reshta Wann',
    position: 'Marketing Executive',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Reshta Wann',
    position: 'Marketing Executive',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Reshta Wann',
    position: 'Marketing Executive',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
  {
    name: 'Reshta Wann',
    position: 'Marketing Executive',
    img: '/images/sheeren.png',
    fb: '',
    email: '',
    linkedin: '',
    instagram: '',
  },
];
export default teamData;
